# This playbook configure ssh access
---
- hosts: "initialize"
  become: yes
  become_method: sudo
  vars:
    hostname: raspberrypi

  tasks:
  - name: "Create user accounts"
    user:
      name: "{{ user }}"
      groups: "adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi"

  - name: "Add authorized keys"
    authorized_key:
      user: "{{ user }}"
      key: "https://github.com/{{ user }}.keys"

  - name: "Allow sudo group without a password"
    lineinfile:
      dest: "/etc/sudoers"
      state: "present"
      regexp: "^%sudo"
      line: "%sudo ALL=(ALL) NOPASSWD: ALL"
      validate: 'visudo -cf %s'

# Network
  - name: "Configure hostname"
    hostname:
      name: "{{ hostname }}"

# Security
  - name: "Disable root login over SSH"
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
      state: present

  - name: "Disable password login"
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
      state: present


# Mount extra volume
  - name: Mount
    mount:
      path: /mnt/volume1
      src: /dev/sda
      opts: bind
      fstype: ext4
      state: present

  - name: "Reboot"
    reboot:
