# This playbook configures the services in rpb
---
- hosts: "rbp"
  tasks:
  - name: "Create directory"
    file:
      path: "~/services"
      state: "directory"
      mode: 0777

  - name: "Copy docker-compose file"
    template:
      src: "services/docker-compose.yaml"
      dest: "~/services/docker-compose.yaml"
      mode: 0777

  - name: "Start services"
    docker_compose:
      project_src: "~/services"
