# This playbook create the initial secure setup for rbp
---

- hosts: "rbp"
  become: yes

  pre_tasks:
  - name: "install python3-pip"
    apt:
      pkg: python3-pip
      state: present

  roles:
  - role: mikolak-net.raspi_config
    raspi_config_hostname: raspberrypi

  - role: geerlingguy.docker_arm
    tags:
      - docker

  tasks:
  - name: "Mount extra storage"
    mount:
      path: /mnt/storage
      src: /dev/sda
      fstype: ext4
      state: mounted

  - name: "Drop the pi user"
    user:
      name: pi
      state: absent
      remove: yes

  - name: "Remove unneeded packages"
    apt:
      autoremove: yes

  - import_tasks: tasks/fail2ban.yaml
    tags: fail2ban

  - import_tasks: tasks/unattended.yaml

    tags: unattended

  - import_tasks: tasks/firewall.yaml
    tags: firewall

  - import_tasks: tasks/docker.yaml
    tags: docker
