---
- name: Cloudflare Dynamic DNS Container
  docker_container:
    name: cloudflare-ddns
    image: oznu/cloudflare-ddns:armhf
    pull: true
    env:
      ZONE: "{{ domain }}"
      API_KEY: "{{ cloudflare_api_key }}"
      SUBDOMAIN: rbp
      PROXY: "false"
    restart_policy: unless-stopped
