---
- name: "Configure ufw (firewall) rules"
  become: yes
  block:
    - apt:
        name: ufw
        state: present
    - ufw:
        rule: allow
        port : "{{ item }}"
      with_items:
        - "22"     # ssh
        - "53"     # dns      (dnsmasq, see below)
        - "80"     # http     (mostly to generate/renew certs)
        - "443"    # https    (mostly to generate/renew certs)
    - ufw:
        state: enabled
        policy: reject
        direction: incoming
