---
- name: "Install and configure unattended"
  block:
  - apt:
      pkg:
        - unattended-upgrades
        - apt-listchanges
        - mailutils
      state: present

  - template:
      src: "unattended/{{ item }}.j2"
      dest: "/etc/apt/apt.conf.d/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - 20auto-upgrades
      - 50unattended-upgrades

- name: "Updated unattended-upgrades config to reboot if needed,
        auto-fix, reboot time, email, etc"
  lineinfile:
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "(\/\/)? ?Unattended-Upgrade::AutoFixInterruptedDpkg \""
      line: Unattended-Upgrade::AutoFixInterruptedDpkg "true";
    - regexp: "(\/\/)? ?Unattended-Upgrade::MinimalSteps \""
      line: Unattended-Upgrade::MinimalSteps "true";
    - regexp: "(\/\/)? ?Unattended-Upgrade::Automatic-Reboot \""
      line: Unattended-Upgrade::Automatic-Reboot "true";
    - regexp: "(\/\/)? ?Unattended-Upgrade::Automatic-Reboot-Time \""
      line: Unattended-Upgrade::Automatic-Reboot-Time "02:00";
    - regexp: "(\/\/)? ?Unattended-Upgrade::Mail \""
      line: Unattended-Upgrade::Mail "{{ email }}";
    - regexp: "(\/\/)? ?Unattended-Upgrade::MailOnlyOnError \""
      line: Unattended-Upgrade::MailOnlyOnError "false";
    - regexp: "(\/\/)? ?Unattended-Upgrade::Remove-Unused-Dependencies \""
      line: Unattended-Upgrade::Remove-Unused-Dependencies "true";
